### ISSUE TITLE
All Categories menu on the top menu is broken #162

### ISSUE THREAD

**Issue by kamrannaqvi** [EsajeeSolutions/Esajeesite#62]
All Categories menu on the top menu is broken and gives NOT FOUND. Could not be fixed via backend

**Comment by sabzesajee** [comment]
fixed

**Comment by kamrannaqvi** [comment]
Sometimes it works fine otherwise its still giving Not Found. See recent screenshot below:

![image](https://cloud.githubusercontent.com/assets/10416359/6590386/d2ad8fe4-c7d0-11e4-8bc6-2fa2b0ded726.png)

**Comment by sabzesajee** [comment]
This was due to server. Now check

**Comment by uuaqarahmed** [comment]
@sabzesajee  this is not due to server and still doesn't work

This happens if we are browsing a sub cat and click on all categories, the path is not calculated properly.

**Comment by sabzesajee** [comment]
@kamrannaqvi  Fixed now

**Comment by kamrannaqvi** [comment]
verified.
